### ISSUE TITLE
Stangenständer

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/iron-temple#1]
Das will wohl nur ich?

Einen Ständer, wo ich meine -- bisher -- zwei Stangen reinstellen kann.
Dachte zuerst an eine vertikale Wandablage, aber das geht im jetzigen
Aufbau platzlich nicht.

Beispiele:
- https://www.megafitness.shop/bar-wall-holder-cue-rack.html
-
https://www.megafitness.shop/atx-barbell-stand-hantelstangen-staender-50-mm.html

Quasi ein Schaft mit 51mm Innendurchmesser, am besten aus Plastik oder
Gummi, um die Stange nicht zu beschädigen. Der Schaft steht dann
entweder am Boden, oder wird seitlich gegen die Wand gemacht.

Optional dann noch eine Fixierung für ein Stück weiter oben -- wobei das
schwer geht mit meinen 2 verschiedenen. Am einfachsten wohl, wenn der
Schaft einfach lang und stabil genug ist.

Gruß

**Comment by cseyda** [comment]
Beni:

Find ich an sich ganz cool, nur Wandbefestigung würd ich bei dir wohl
lieber nicht machen. Normalerweise entstehen zwar keine Kräfte an den
Haltern,
aber wenn doch mal jemand doof gegen die Stange kommt, haben wir hier
halt nen ziemlich heftigen Hebel, der wohl das Dingens aus der Wand
reißen könnte.

Am besten am Boden und nach Möglichkeit mim Rack verbunden, damit wir
hier kein großartiges Gestell bauen müssten?

**Comment by cseyda** [comment]
besonders bei meinen wänden...

**Comment by cseyda** [comment]
Robin:

Das was der Beni sagt macht Sinn. Ich brauche wohl keine Haltung, würde es aber direkt am Rack aber auch praktischer finden.

Könnte man da nicht sowas ähnliches wie eine Pfostenhalterung (https://toolineo.de/aufschraubhuelse-tzn-91-vierkant-p!100000000092407.html?h=0000140&pla=ab&utm_content=0&gclid=CjwKCAjw0tHoBRBhEiwAvP1GFbommD2hKJj3lpTLElycAkWPOXQE4tYvl51tVLhMp05Su9ChgFv5DhoCYUoQAvD_BwE) an den Boden vom Rack setzen und weiter am oben am Rack irgendeine Absicherung? Wenn die Stange unten in der Halterung wäre, müsste man nur jedes Mal irgendeine Art "Eisenring" haben, den man an der Stange ansetzen kann und festziehen muss. Falls das überhaupt Sinn macht, was ich schreibe? :D

**Comment by cseyda** [comment]
Beni:

Ist auf jedenfall ne gute Idee. Muss man nur schauen, obs sowas passend für ne 50er Stange in rund gibt. Bzw mit genug Aufmaß, damit man da nen Kunststoffring einpressen könnte.
Wenn das am Boden gut mim Rack verbunden ist, brauch man eventuell nicht mal oben etwas... glaub ich?

Platz muss man halt noch abklären.

**Comment by cseyda** [comment]
Macht sogar Sinn Robin :wink: 
Die große Stange würde bei mir neben das Rack passen von der Höhe. Jedoch muss dann die Fassung am Boden lose/flexibel sein.

**Comment by cseyda** [comment]
@Acidburn707 vllt sowas:
https://www.garage-gyms.com/diy-barbell-rack-bar-storage/
Clips um die Stange am Rack festzuklemmen. Könnte man ja am kleineren Vierkant-befestigen. Ggfs eine Sicherunge, damit sie nicht setlich rausfallen können a la Gürtel / lösende Kabelbinder.

**Comment by Acidburn707** [comment]
Dann machen wir deine beiden Stangen jeweils seitlich an einen Spotterturm?

Hab mir überlegt, dass unten die Fassung kippbar ist. D.h. man steckt die Stange rein und drückt sie anschließend Richtung Turm in so nen Clip wie aus dem Link rein?

**Comment by cseyda** [comment]
wenn die latzug-stange dann noch hinpasst, klingt das gut.

ich messe mal aus, wieviel platz zur decke ist, wenn die stange auf dem boden steht? nicht, dass es am ende zu hoch wird...

**Comment by cseyda** [comment]
12cm hab ich maximum platz zwischen stange und decke.

**Comment by Sem17** [comment]
> Das will wohl nur ich?

Also Ich hab das Platzproblem an der Wand nicht, aber das mit der Decke im Keller. 
Bei 2,15m Deckenhöhe und 2,20m Stange ist da keine Möglichkeit die gerade ans Rack zu stellen.

Ich bleib also bei Haken an der Wand^^

**Comment by Acidburn707** [comment]
Mach ich jetzt ein wenig anders. Das mit kippbarer Fassung wird recht kompliziert bzw zu aufwendig, weil du so wenig Luft nach oben hast.

Stattdessen kommt da jetzt einfach ne flache Ablage aufn Boden. Die Stange zentriert sich mittig auf dieser Ablage, weil Schrägen dran sind und oben wirds dann nach wie vor eingeklippt. Zeichnung kommt morgen.

**Comment by Acidburn707** [comment]
[Haltearm für Stange.pdf](https://github.com/Kirchenchor/iron-temple/files/3868727/Haltearm.fur.Stange.pdf)

Einmal der Arm an sich. Wird an einer bestehenden Bohrungen festgeschraubt und schlängelt sich dann nach unten bis auf den Boden. Die Befestigungsbohrung ist ein Langloch, d.h. man kann den Arm ein wenig in der Höhe verstellen. Einfach um Toleranzen oder auch Bodenunterschiede auszugleichen.

**Comment by Acidburn707** [comment]
[Teller für Haltearm.pdf](https://github.com/Kirchenchor/iron-temple/files/3868732/Teller.fur.Haltearm.pdf)

Das ist der Teller, in welcher dann die Stange eingesetzt wird. Ist aus Kunststoff und wird mit einer Schraube zentral am Arm befestigt.

**Comment by Acidburn707** [comment]
https://www.ebay.de/itm/Kunststoff-Klemmschelle-Rohrschelle-M16-M63-lichtgrau-halogenfrei/173830499557?hash=item28791aece5:m:moN-2nH6rAivDIlNZm8ypgA

Sowas nehmen wir als Klipp, für oben. M50 passt für Chris. Wegen M32 bei den 30er Stangen müssen wir mal sehen.

**Comment by cseyda** [comment]
:+1:

**Comment by Acidburn707** [comment]
Achso, deshalb hast du wegen den Klipps in WA gefragt. Jo, verkackt, bei dir brauchen wir wie gesagt auch dann M32.

**Comment by cseyda** [comment]
wieviele stangen könnten wir so sinnvoll unterbringen?
auch die neue Hex-Stange?

**Comment by Acidburn707** [comment]
Mit dem jetzigen System sind SZ und normale Barbell möglich. (wobei ich das verpeilt und für jeden von uns bisher nur 1 eingeplant hatte :P. Ist aber korrigiert)
Die Hex ist relativ klobbig. Würd da wohl warten, bis alles steht und dann nen Platz suchen?
