### ISSUE TITLE
Boxsackhalter

### ISSUE THREAD

**Issue by Acidburn707** [Kirchenchor/iron-temple#11]
todo

**Comment by Sem17** [comment]
theoretisch tuts  da doch ein Haken, der an der gleichen Mittelführung( welche jene an der 30mm Stange mittig sitzt) festgemacht werden kann, wie die Rolle vom Latzug?

**Comment by Acidburn707** [comment]
Du meinst die Klimmzugstange denke ich mal? Prinzipiell, nur hängt da dann halt neber der Rolle noch irgendwas rum. Wenns also gewünscht wäre, könnte ich da was machen, was man dann wie die Rolle festklemmen kann und falls nicht benötigt auf die Seite schiebt.

**Comment by Acidburn707** [comment]
Meine Version, die ich haben möchte:

[Boxsackhalter.pdf](https://github.com/Kirchenchor/iron-temple/files/3906939/Boxsackhalter.pdf)

**Comment by cseyda** [comment]
so in der richtung hab ich mir das auch vorgestellt.
müsste man vllt noch ne stange weiter unten hinter den sack führen, dass er nicht zu sehr herumschwingt?
mal gucke'.

**Comment by Acidburn707** [comment]
Auch hier gabs ein Problem. Bin von Löchern ausgegangen, die es so nicht gab und die bei Sebl und mir nach unten verschobene Klimmzugstange war quasi im Weg.
Neue Version ist alles berücksichtigt:

**Comment by Acidburn707** [comment]
Neue Version, auch hier waren Fehler drin. Bin von Löchern ausgegangen, die es nicht gab und die bei Sebl und mir versetzte Klimmzugstange war im Weg.

**Comment by cseyda** [comment]
ich kann editieren zumindest, war wohl nur zum Zeitpunkt des Postens nicht möglich?

**Comment by Acidburn707** [comment]
[Boxsackhalter.pdf](https://github.com/Kirchenchor/iron-temple/files/4169659/Boxsackhalter.pdf)
 
Jo... jetzt gehts wieder.
