### ISSUE TITLE
IKEA

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/iron-temple#13]
Sebastian will ja ein Regal kaufen, ich schau gerade nach einem besseren Regal für mein Sportzubehör, da kann man das ja poolen.
~~Beides nicht großartig wichtig, deswegen kann ja jeder sich kurz Gedanken machen, ob er noch mehr braucht -- eventuell ein IKEA Ausflug zusammen ^^~~

Beni:
Bill Regalbrett https://www.ikea.com/de/de/p/billy-extra-regalboden-eichenfurnier-weiss-lasiert-00404275/

**Comment by Acidburn707** [comment]
Der gemeinsame Ikea Besuch hat sich ja leider erstmal erledigt...

Aber ich hab natürlich verkackt, genug Billy Regalbretter zu holen. Würde also noch 1 mitbestellen.
https://www.ikea.com/de/de/p/billy-extra-regalboden-eichenfurnier-weiss-lasiert-00404275/
