### ISSUE TITLE
Urlaub

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/iron-temple#14]
Ziele / Aktivitäten für Bodensee sammeln.
Gebucht wird kurzfristig, je nach Corona Situation.

Alternativen schauen für hier Umgebung.

**Comment by burningox** [comment]
Aus Urlaubsplanung wird eine Tagesausflugsplanung.

**Kanu:**

Kanufahrt auf Neckar oder Kocher. Jagst ist durch häufig niedrigeren Pegelstand schlechter zu planen. Mein Favorit wäre der Kocher, da dort die Fahrtatmosphäre ruhiger erscheint und der Fluss wendungsreicher ist.

Fahrten wären zwischen 3-4 Stunden lang (bei der 4 Stunden-Fahrt wäre eine Mittagspause dabei) und man bräuchte ca 1 bis 1:30 Stunden mit dem Auto, bis man am Start-Ort ist. Kosten scheinen bei ca. 30 Euro pro Person zu liegen.

Buchung steht noch aus, Anfragen zu Touren sind raus.

https://www.kanu-bike.de/kanutouren/kanutouren-kocher/gemuetliche-tages-kanu-tour-moeglingen-kochertuern/

https://www.kanu-bike.de/kanutouren/kanutouren-neckar/3-stunden-tour-obrigheim-neckargerach/


**Wandern:**

Wandertour ist in Planung. Optionen "vor Ort" wären vorhanden. Eine Tour in Heidelberg/Philosophenweg/Thingstätte ist bereits auf komoot erstellt worden. 

https://www.komoot.de/tour/206855679

Tourdauer (mit Anfahrt) ca. 4 Stunden. Zeit wurde (unrealistisch :D ) ohne Pausen gerechnet. Start der Tour ist am Bismarckplatz, Ende der Tour ist in der Altstadt-Bahnhof. Danach besteht die Option was in Heidelberg zu bleiben, oder mit dem Zug nach Hause zu fahren.

Anderer Wanderrouten (auch mit möglicher "weiterer Anfahrt") können noch geplant werden. @Acidburn707  hat noch die Option ins Spiel gebracht, eine Wanderung mit Ziel Campingplatz/Zelten zu planen. 

**Fahrradtour** 

Fahrradtouren sind ähnlich wie die Wanderrouten. Nachdem @cseyda und @burningox  bereits eine Tour geplant und durchgeführt haben, können jetzt die nächsten "Standardtouren" folgen. Weitere Routen sind bereits in Planung @Sem17  (oder bereits bei komoot gespeichert). In Überlegung sind auch lange Touren (3-4 Stunden .. oder mehr?), die gemütlich zu fahren sind und mit Essenspausen/Points of interest gefüllt werden können. Offen ist, wie beim Wandern, das Ziel der Tour: Zelten, Camping, Lagerfeuer ....

**Comment by burningox** [comment]
**Update Kanu:**
 
Meine Favoritentour (Möglingen nach Kochertürn) ist noch für den Mittwoch, 22.7, buchbar. Yes 😄 

https://www.kanu-bike.de/kanutouren/kanutouren-kocher/gemuetliche-tages-kanu-tour-moeglingen-kochertuern/

Die andere Tour (Obrigheim nach Neckargerach) wäre nur am Freitag, 24.7, möglich. 

Gedanken müsste man sich noch über den Personentransport machen. Entweder wir fahren mit zwei Autos, oder wir wir nehmen den Service in Anspruch, dass mindestens eine Person zum Auto am Startort gebracht wird. Der Fahrer (der wäre laut Mail im Preis inbegriffen) würde dann vor oder nach der Tour zum Auto gebracht werden, oder jeder zahlt 3 Euro und alle würden per Bus zum Auto gebracht werden. Ob das vor oder nach der Tour passiert, wird erst mit der Buchung klar.

**Comment by cseyda** [comment]
Mo
1002 Zug (Altstadt)
Wandern: Robin Route
Essen für unterwegs mitnehmen
mit 5-6 Stunden rechnen
Maske

Di 
frei

Mittwoch, 22.7
Abfahrt 0845
0830 @burningox 
0835 @cseyda 
0840 @Acidburn707 
Maske

dannach
Coach Coop + Burger Grillen
kaufen auf Heimfahrt?
beim @Sem17 

Do
Fahrrad fahren, Sebastian Tour
16-18
dann Garten + Grillen

Fr
frei

Sa
1000 zusammen "Training"
(Essen? To be discussed)
Meeting
abends Spielen

So
frei
