### ISSUE TITLE
MyProtein

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/iron-temple#15]
Kreatin
FlavorDrops
NussMus
Granola
Granola 2

**Comment by burningox** [comment]
Ich passe bei dieser MyProtein-Bestellung. Habe aktuell noch alles in stock.

**Comment by Acidburn707** [comment]
[chocolate](https://de.myprotein.com/sporternahrung/choc-chunky-proteinriegel/11431044.html)
[chocolate sundae](https://de.myprotein.com/sporternahrung/6-layer-proteinriegel/12116519.html)
[hazelnut](https://de.myprotein.com/sporternahrung/protein-bar-elite/11281385.html)

**Comment by cseyda** [comment]
@Acidburn707 Dennis wollte ja auch noch, wenn ich mich recht erinnere?

**Comment by Acidburn707** [comment]
Die ersten beiden sind fürn Dennis, das letzte für mich.

**Comment by Sem17** [comment]
Ich passe auch, ich hab noch alles was ich brauch
