### ISSUE TITLE
Bestellung: https://www.teegschwendner.de/

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/iron-temple#18]
https://www.teegschwendner.de/

Wann: Anfang des Monats. Wer nichts schreibt, bekommt nicht mitbestellt.

**Comment by Sem17** [comment]
jeweils 100gr.
[Nr.938](https://www.teegschwendner.de/tee-shop/earl-grey?c=236), 6,20€
[Nr.923](https://www.teegschwendner.de/tee-shop/earl-grey-imperior) 5,90€
[Nr.430](https://www.teegschwendner.de/tee-shop/ceylon-nuwara-eliya-highgrown) 4,90€
und denk dran
[kostenlos](https://www.teegschwendner.de/teelamass-gruen-blau-rot)

**Comment by cseyda** [comment]
ab sofort bestelle ich, wann ich lust habe.
