### ISSUE TITLE
Alcohol

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/iron-temple#19]
stuff to buy:
- [ ] [Frangelico Nuss](https://www.conalco.de/frangelico-haselnusslikoer-0-7l-20-vol): (18,31€ / L) 
- [ ] [Mintuu](https://www.conalco.de/minttu-50-0-5l-50-vol): 0.5L, 9,38€ (19€/L) 
- [ ] [Kruskovac](https://www.conalco.de/kruskovac-svatovski-birnen-likoer-badel-1-liter-24-vol): 1L, 9€
- [ ] [Kahlua Kaffee](https://www.conalco.de/kahlua-kaffeelikoer-1-liter-20-vol): 1L, 16,67€
- [ ] [Lakritzlikör](https://www.conalco.de/koskenkorva-salmiakki-pet-0-5l-30-vol): 0,5L 7€, (14€/L)
- [ ] [Nordbrand Pfeffi](https://www.conalco.de/nordbrand-pfeffi-pfefferminz-likoer-1-liter-18-vol) 1L, 5,6€
- [ ] [Orange](https://www.conalco.de/le-favori-triple-sec-liqueur-a-lorange-0-7l-40-vol): 0,7L, 10€ (15€/L)
- [ ] [Kirsche](https://www.conalco.de/maraschino-zadarski-maraska-kirsche-1-liter-32-vol): 1L, 15€
- [ ] [Karamell](https://www.conalco.de/cuba-caramel-karamellikoer-0-7l-30-vol): 0,7L, 11€ (16€/L)
- [ ] [Vanille](https://www.conalco.de/szene-licor-doro-original-vanillelikoer-1-liter-31-vol): 1L, 12,28€
- [ ] [Minttu Polka](https://www.conalco.de/minttu-twist-polka-likoer-0-5l-16-vol): 0,5L, 7,21€ (15€/L)
- [ ] [Minttu Bubblegume](https://www.conalco.de/minttu-twist-bubble-gum-likoer-0-5l-16-vol): 0,5L, 7,21€ (15€/L)

--
~122,93€
=> 160€ max

+ Rewe Melonenschnaps Sorten

**Comment by Acidburn707** [comment]
Lakritze find ich absolut ekelhaft, aber als Likör hab ich keine Ahnung. [Kettenfett](https://www.conalco.de/kettenfett-lakritzlikoer-0-5l-25-vol) klingt aber witzig xD
[Orangenlikör](https://www.conalco.de/le-favori-triple-sec-liqueur-a-lorange-0-7l-40-vol) fänd ich interessant und [Kirsche](https://www.conalco.de/maraschino-zadarski-maraska-kirsche-1-liter-32-vol)
[Karamell?](https://www.conalco.de/cuba-caramel-karamellikoer-0-7l-30-vol)

**Comment by cseyda** [comment]
Lakrize hatten wir mal, glaube ich, und Meinungen waren gespalten.
Deswegen hätte ich einen billigeren probiert als Kettenfett ;)

**Comment by Acidburn707** [comment]
Okay, weiß ich nicht mehr. Können wir aber gerne nochmal versuchen.

**Comment by cseyda** [comment]
of course. mir hatte er geschmeckt iirc :P

**Comment by burningox** [comment]
Lakritze meine ich auch, dass wir den schon einmal hatten. Aber ich hab keine Erinnerung mehr an den Geschmack. Also warum nicht 😅

Ich hätte sonst noch [Vanille](https://www.conalco.de/szene-licor-doro-original-vanillelikoer-1-liter-31-vol) spannend gefunden. Und eigentlich auch Honig, der aber wegm Sebl rausfällt.

Orange bin ich auch gespannt, Kirsche hoffe ich, das er süß ist. Pfeffer brauch ich nicht 😂 Der Rest sieht gut aus 😊

**Comment by Sem17** [comment]
[Minttu Laktritze](https://www.conalco.de/minttu-black-mint-likoer-0-5l-35-vol)
den könnten wir ausprobieren, ist auch nicht allzu teuer 8,65€
den [Minttu BubbleGum](https://www.conalco.de/minttu-twist-bubble-gum-likoer-0-5l-16-vol) und den [Polka](https://www.conalco.de/minttu-twist-polka-likoer-0-5l-16-vol) würd ich noch gern ausprobieren

> Ich hätte sonst noch Vanille spannend gefunden. Und eigentlich auch Honig, der aber wegm Sebl rausfällt.

Von Vanille bin ich im Normalfall kein Fan, können wir aber gerne ausprobieren, wenn dadurch das Gift ausm Garten fernbleibt^^

> Orangenlikör fänd ich interessant und Kirsche

*thumbs up*
>Karamell?

Hab ich die gleichen Bedenken wie bei Vanille, aber probieren geht über studieren

**Comment by Acidburn707** [comment]
Sebl bekommt neuen Pokal: "Minttu Fanboy"

**Comment by Sem17** [comment]
> Sebl bekommt neuen Pokal: "Minttu Fanboy"

hab ich nix dagegen, wenn er so aussieht wie ne Minttu Flasche, man ihn aufschrauben kann, und da Minttu drin ist :P

**Comment by cseyda** [comment]
Lakritze würde ich schon gerne nur Lakritze holen, nicht Lakritze-Mint

**Comment by cseyda** [comment]
178.20 - 122.93 = 55.27
122.93 / 4 ~ 30.74

Robin + Beni: 30.74
Sebastian: 30.74 + 55.27 = 86.01

wie immer kurz Kopf anmachen und überfliegen, ob das Sinn macht
bei Gelegenheit kann ich auch PP links verschicken

**Comment by Sem17** [comment]
bezahlt. versand geht an mich? da ich ja am meisten "stakes" in der lieferung habe? :)

**Comment by cseyda** [comment]
versand geht an mich, weil ich bestellt hab... und auch praktisch immer daheim sein kann
