### ISSUE TITLE
Deadlift Jack

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/iron-temple#2]
Das ist so der standard DIY jack:
http://www.endofthreefitness.com/how-to-build-a-mini-deadlift-jack/

﻿kleinere, effizientere Version:
https://forum.bodybuilding.com/showthread.php?t=153725251

mir gefällt die Version am besten:
https://www.reddit.com/r/Fitness/comments/40ou3z/5_homemade_mini_deadlift_jack_tested_at_625lbs/

Sieht stabiler aus, macht meinen Boden weniger kaputt, und sieht nicht
nach Klemptner aus.

Gruß

**Comment by cseyda** [comment]
Beni:

Die Holzversion gefällt mir am wenigsten. Klar, funktioniert, aber wenn ich sowas bau oder mir kaufe, dann will ich auch Komfort beim anheben haben.

Durch den kleinen Hebel muss man vergleichsweise stark drücken und sich auch noch am Gewicht gegenhalten.

Ich wär für ne Metallversion ähnlich wie die einfachen Motorradheber (https://www.ricambiweiss.com/de/montagestaender/montagestaender-hinten/stt-montagestaender-hinterrad-universal.html).
Brauch natürlich nicht so massiv ausgeführt sein. :D

**Comment by cseyda** [comment]
Robin:
Gute Idee!

Mit dem Mottoradheber für 20 Euro würde das auch noch nicht einmal viel kosten. Weil ja, der sieht nicht so aus, als würde er am Boden was kaputt machen können. Ich kann da bei den Metallversionen nicht einschätzen, was da den Laminat verkratzen könnte.

**Comment by cseyda** [comment]
Beni:

Hast du da was falsch verstanden? ^^

Mit so nem Motorradheber an sich würds natürlich auch gehen, aber der ist ein wenig arg groß. Ich würd dann genau sowas nur in kleiner bauen. Auflageflächen sind dann gummiert und ob man Rollen brauch, muss man eben checken. Glaube aber eher nicht.

**Comment by burningox** [comment]
Ah, ok. Dann hab ich das falsch verstanden mit dem Motorradheber ^^

Wenn es gummiert ist, dann bin ich zu 100% dafür. Rollen denke ich auch nicht, dass man die braucht.

**Comment by Acidburn707** [comment]
Das hier fand ich ziemlich geil, bzw so ähnlich hab ich mir das auch vorgestellt. Allerdings stabiler und weniger wacklig: https://www.youtube.com/watch?v=D2068p7VCBg

**Comment by cseyda** [comment]
scoop :)
jo, das ding sah nett aus. kam mir nur schwer zu machen vor.
das bekommst du hin?

**Comment by Sem17** [comment]
Hatte er was gesagt, bei nem Meeting ob er den Genesis nachbauen kann?
Weil das Ding sieht schon praktisch aus, eben genauso wie der kleine selbstgebaute aus Holz, nur noch Platzsparender.

**Comment by Acidburn707** [comment]
Einmal 50mm Deadlift Jack:

[Deadlift Jack (50mm).pdf](https://github.com/Kirchenchor/iron-temple/files/3874206/Deadlift.Jack.50mm.pdf)

**Comment by cseyda** [comment]
machst du 30 und 50mm versionen? wenn ja, wozu? :sweat_smile:

**Comment by Acidburn707** [comment]
Haben ja unterschiedliche Scheibendurchmesser. Bei der Bearbeitung machts eh keinen Unterschied. Wird nur unterschiedlich lang abgesägt. Rest ist gleich.

**Comment by Acidburn707** [comment]
Irgendwas ist beim PDF Export verkackt gewesen. Hier nochmal beide Versionen:

[Deadlift Jack (50mm).pdf](https://github.com/Kirchenchor/iron-temple/files/3879167/Deadlift.Jack.50mm.pdf)

[Deadlift Jack (30mm).pdf](https://github.com/Kirchenchor/iron-temple/files/3879168/Deadlift.Jack.30mm.pdf)

**Comment by cseyda** [comment]
jetzt erkennt man auch was ;)
wegen dem hexbar müssen wir dann halt schauen. je nach auflagefläche kann man vielleicht einen aufsatz oder so machen?

**Comment by Acidburn707** [comment]
[Schonplatten für Deadlift Jack.pdf](https://github.com/Kirchenchor/iron-temple/files/3907004/Schonplatten.fur.Deadlift.Jack.pdf)

**Comment by Acidburn707** [comment]
Ich überleg mir noch was für die Hexbar.

**Comment by cseyda** [comment]
was sind schonplatten?

**Comment by Acidburn707** [comment]
Kratzschutz für Barbell

**Comment by cseyda** [comment]
es gibt leider anscheinend nichts für hexbars
https://forum.bodybuilding.com/showthread.php?t=163843661

werd das innen als bock benutzen, um die letzen beiden scheiben runter zu bekommen, und bei mehr dann eben der scheibe unter scheibe "trick".

**Comment by cseyda** [comment]
done
