### ISSUE TITLE
Weighttree

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/iron-temple#5]
Guten Morgen!

Wie der Weighttree grundlegend ausfallen muss, ist mittlerweile klar.

Details in der Ausführung könnten noch variieren, aber folgendes konnte
ich noch nicht klären:

- Ich habe noch nicht gefunden, wie man am geschicktesten die neuen 40er
Vierkantrohre für die Gewichte auf unsere 80er am Boden liegend montiert.

Es gibt keine Schraublöcher an der Position.
Einfach darauf stehen lassen mit Gummipuffer dürfte sogar funktionieren,
wobei ich mir doch ein wenig mehr Sicherheit wünsche.
Eine Art U-Profil zum Überstülpen auf die 80er? Und Verbunden mit einer
Schweißnaht? Hab dazu leider nur längere Profile gefunden, die man dann
zuschneiden müsste, und nach kurzem Schauen auch nicht sofort passende
Maße gefunden.

Gruß

PS: Ihr dürft gerne auch selbst darüber Nachdenken, Planen und Schauen.

**Comment by cseyda** [comment]
Beni:

Genau, quasi.

An die 40er Rohre kommen jeweils 20mm Stahlstücke rechts und links dran, damit
wir auf dem gleichen Maß wie die 80er Rohre sind und dann nochmal zwei
Verbindungsstücke von 40er zu 80er. Dann haben wir unser "U".

An die Verbindungsstücke könnt man dann vielleicht noch Schrauben hinmachen,
um gegen das Rack zu klemmen und somit verrutschen zu verhindern.


Gruß

**Comment by cseyda** [comment]
:thinking: 
also quasi pro Seite 2 L-Leisten?

40 |_
.... _
80..   |

**Comment by Acidburn707** [comment]
Den Gewichtsturm mach ich was Lochabstand angeht auf jeden maßgeschneidert, da es keinen Unterschied macht, wo ich die Löcher bohren muss.

Hier einmal Chris Variante, bitte drüber schauen, ob ich mich von den Maßen vielleicht doch verhuddelt haben sollte:
![WhatsApp Image 2019-08-28 at 11 52 33](https://user-images.githubusercontent.com/37957957/63845760-c805bd80-c98a-11e9-838c-f962fd9b31db.jpeg)

**Comment by cseyda** [comment]
ok, sollte passen.
können wir vorher versuchen ob 30er aufnahmen praktisch wären? oder ob das zu arg wackelt dann.
manchmal nervig, so gerade rausziehen zu müssen.

**Comment by Acidburn707** [comment]
Am Anfang wolltest die ja noch enger haben... 😅
Aber klar, ich kann dir ja grad Mal die 30er Aufnahme geben

**Comment by Acidburn707** [comment]
Auf welcher Höhe kann ich denn die Verbindungsstrebe von Gewichtsturm zu Hauptturm machen? Könnt ihr bei euch mal schauen, wo Löcher belegt sind für Bench, Squat, Spotter, etc.? Aber nur die Höhe vom Turm, also nicht vom Boden aus messen.

**Comment by cseyda** [comment]
alle Angaben sind vom Turm von oben nach unten als belegt zu lesen:

Squat: Löcher 3-5 aka 58-69cm
Bench: Löcher 12 + 13 aka 103-109cm
Spotter: 22 + 27 aka 131 + 144cm

**Comment by Acidburn707** [comment]
Sorry, ich bin von ausgegangen, dass man von unten nach oben misst. xD Kannst du das bitte nochmal machen?
Für die anderen auch: Von unten nach oben messen.

**Comment by Acidburn707** [comment]
Zeichnungsskizzen für Gewichtsturm:

![WhatsApp Image 2019-08-31 at 19 04 48](https://user-images.githubusercontent.com/37957957/64067092-02898780-cc23-11e9-8045-560aa6a8ecb0.jpeg)

**Comment by cseyda** [comment]
Squat: Löcher 33-35 aka 132-142cm
Bench: Löcher 25 + 26 aka 93-98cm
Spotter: 11 + 16 aka 57 + 70cm

**Comment by Sem17** [comment]
Squat L35+36 142-149cm
Bench L26+27 96-104cm
Spotter L10 55cm; L16 70cm

**Comment by burningox** [comment]
Spotter:

- Row-Ablage: L 6 - 45 cm
- Bench: L 13 - 63 cm
- (Incline/Squat): L 18 - 76 cm

J-Hooks:

- Bench: L 27 und 28 - 102/108 cm
- Incline: L 30 und 31 - 118/123 cm
- Squat: L 36 und 37 - 147/152 cm

**Comment by Acidburn707** [comment]
Thanks Mates.
Strebe zum Hauptturm wird sich dann bei L20 - 80cm befinden.

**Comment by Acidburn707** [comment]
[Gewichtsturmverbindung.pdf](https://github.com/Kirchenchor/iron-temple/files/3881671/Gewichtsturmverbindung.pdf)

Verbindet die beiden Gewichtstürme miteinander für mehr Support.

[Gewichtsturm 30mm.pdf](https://github.com/Kirchenchor/iron-temple/files/3826563/Gewichtsturm.30mm.pdf)

Der Gewichtsturm als 30mm Scheiben Version.

**Comment by Acidburn707** [comment]
[Gewichtsturm 50mm.pdf](https://github.com/Kirchenchor/iron-temple/files/3828907/Gewichtsturm.50mm.pdf)

Der Gewichtsturm als 50mm Scheiben Version.

**Comment by cseyda** [comment]
> [Gewichtsturm 50mm.pdf](https://github.com/Kirchenchor/iron-temple/files/3828907/Gewichtsturm.50mm.pdf)
> 
> Der Gewichtsturm als 50mm Scheiben Version.

best version <3

**Comment by Acidburn707** [comment]
[Verbindung Gewichtsturm zu Gewichtsarm.pdf](https://github.com/Kirchenchor/iron-temple/files/3828971/Verbindung.Gewichtsturm.zu.Gewichtsarm.pdf)

Die "Äste" an denen dann die Scheiben hängen sind nicht geschweißt, da die Vierkantrohre verzinkt sind. Stattdessen werden die mit Stahlbrocken verbunden.

[Gewichtsarm.pdf](https://github.com/Kirchenchor/iron-temple/files/3828972/Gewichtsarm.pdf)

Ein "Ast" am Gewichtsbaum.

[Strebe Gewichtsturm zu Hauptturm.pdf](https://github.com/Kirchenchor/iron-temple/files/3828974/Strebe.Gewichtsturm.zu.Hauptturm.pdf)

Für mehr Stabilität.

[Verbindung zu Boden.pdf](https://github.com/Kirchenchor/iron-temple/files/3828975/Verbindung.zu.Boden.pdf)

2 Brocken die miteinander verschweißt sind. Werden dann in die Bodengruppe eingesetzt und durch das Verschrauben verklemmt.

**Comment by Acidburn707** [comment]
[Neue_Hauptturmverbindung.pdf](https://github.com/Kirchenchor/iron-temple/files/3881674/Neue_Hauptturmverbindung.pdf)

Die 30er Stange abgesägt dann als Klimmzugstange.

**Comment by cseyda** [comment]
done
