### ISSUE TITLE
Band pegs aka Gummihalter(?)

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/iron-temple#8]
Damit man Gummis fixieren kann, um gegen den variablen Widerstand zu trainieren.

**Comment by Acidburn707** [comment]
Quasi ein Haken, um ein Gummi einzuhängen oder?

**Comment by cseyda** [comment]
eigentlich nur ein stift. das gummi sollte ja nicht rutschen, und die kraft sollte nur horizontal (hoch /  runter oder vor / zurück) ausgeübt werden.

**Comment by cseyda** [comment]
![](https://www.roguefitness.com/media/catalog/product/cache/1/image/1500x1500/472321edac810f9b2465a359d8cdc0b5/b/a/band-pegs-1_1.jpg)

**Comment by Acidburn707** [comment]
[Band Pegs.pdf](https://github.com/Kirchenchor/iron-temple/files/3754758/Band.Pegs.pdf)
