### ISSUE TITLE
Landmine

### ISSUE THREAD

**Issue by Acidburn707** [Kirchenchor/iron-temple#9]
Ist zwar nochn wenig wacklig, aber da ich schon Skizzen für gemacht hab:

![Landmine1](https://user-images.githubusercontent.com/37957957/64067138-f7832700-cc23-11e9-8fd6-b83eecf3d9f6.jpeg)

**Comment by cseyda** [comment]
ich erkenne da immer noch nicht viel ;)

**Comment by Sem17** [comment]
Hatte Ich ja bei nem Meeting gesagt, die "Poor Mans Landmine" oder wie man das nennt, erfüllt den Zweck genauso, 
und abgesehen von Abwechslung beim Training bringt es an sich nichts.
Kann Ich also drauf verzichten.
